# Generated by Django 3.0.7 on 2021-01-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.CharField(choices=[('Emergency', 'Emergency'), ('Moderate', 'Moderate'), ('Normal', 'Normal')], default='None', max_length=100),
        ),
    ]
